### ISSUE TITLE
No Such Function: ST_MinX

### ISSUE THREAD

**Issue by abucklecslt** [opengeospatial/ets-gpkg12-nsg#10] opened 2018-03-23 11:05 UTC
Hi,

I ran the NSG GeoPackage 2.1 test from the OGC Validation Web Site against a geopackage. The NSG Data Validity test case failed with the following error:

"java.sql.SQLException: 
[SQLITE_ERROR] SQL error or missing database (no such function: ST_MinX)"

I believe it may be an issue with the NSG GeoPackage 2.1 test case. The function ST_MinX() should be supplied when loading the SpatiaLite drivers. Maybe the loading of the SpatiaLite drivers are failing when the test case is ran.

**Comment by dstenger** [comment] 2018-03-26 12:01
@jyutzler 
Does this error message sound familiar to you? If this is the case, can you please provide details about it?

@abucklecslt 
Can you please provide a test dataset we can use to reproduce the error?

**Comment by jyutzler** [comment] 2018-03-26 19:04
@dstenger I don't own the NSG GeoPackage 2.1 profile or its ETS but it seems strange to me that either would have a dependency on SpatiaLite. This should be brought to the attention of whoever owns those products.

**Comment by dstenger** [comment] 2018-03-27 07:20
@keshav-nangare 
Can you take a look at this issue?

**Comment by abucklecslt** [comment] 2018-03-29 16:16
Attached is a sample dataset that will cause the error.

Regards,
Anthony

**Comment by keshav-nangare** [comment] 2018-04-02 13:01
@abucklecslt 

Can you please provide the dataset in issue tracker? I think it's not uploaded.

**Comment by abucklecslt** [comment] 2018-04-02 13:13
The following geopackage dataset will reproduce the issue.

[CSLT_Canada.zip](https://github.com/opengeospatial/ets-gpkg12-nsg/files/1868129/CSLT_Canada.zip)

**Comment by abucklecslt** [comment] 2018-04-02 13:14
I uploaded the requested dataset as a zip.

**Comment by keshav-nangare** [comment] 2018-04-03 14:06
@abucklecslt 

I have tested the dataset with the ets and found following observations.

`SELECT column_name FROM gpkg_geometry_columns WHERE table_name='CAN_CSLT_ROUTES'; Output==>> Shape[Column_name]`

By using output above query, following query is executed

`SELECT ST_MinX(Shape) AS theResult FROM CAN_CSLT_ROUTES;`

And this query is failed with the reported error because the table `" CAN_CSLT_ROUTES"` is null.

Can you please check this table?

**Comment by abucklecslt** [comment] 2018-04-03 14:08
Thank you for your help. I will review.

**Comment by ajanett** [comment] 2018-04-12 21:20
The NSG GeoPackage 2.1 test suite has apparently got one and only one 'feature' related test in it at the moment and you managed to hit it.  A detailed explanation is forthcoming.

**Comment by gtrenum** [comment] 2018-04-12 21:28
Please accept my apologies in advance for the length of this comment.

The earlier comment "The function ST_MinX() should be supplied when loading the SpatiaLite drivers. Maybe the loading of the SpatiaLite drivers are failing when the test case is ran." Is relevant, but not complete. The ST_Geometry function calls are included in the Spatialite extensions and are not native to SQLite. The NSG and OGC standards for GeoPackages specifically call out the ST_MinX and several other ST_Geometry functions in their tests. However, the test code does not include the Spatialite extensions to the SQLite database and so we would expect all of the ST_Geometry function calls to behave similarly. It is also worth noting that the current NSG test code making the calls to ST_MinX etc. is performing this test on the features. This is the only 'feature' test in the NSG GeoPackage test code.

There has been discussion about not wanting the NSG standards to have any GeoPackage tools dependent on the full Spatialite extensions. However, the way the standard is written, it is explicitly dependent on them (see the SQL test statements). Also, while the NSG Standard or GeoPackage explicity calls out SQLite support, is does not explicitly mention Spatialite extensions. The way the GeoPackage test tools are all coded, SQLite is opened in a manner that does not allow extensions. The GeoPackage standards do call out the "GeoPackage SQLite Configuration" settings and those settings do not include the settings needed for extensions. This part of the standard should be corrected to allow for extensions if the previously described extensions are really wanted.

As far as corrective action is concerned, we see two options; either update the test code to include the Spatialite extensions or write custom extensions/custom code to support the functionality needed to execute the NSG Profile tests.

**Comment by melvchan** [comment] 2018-04-13 14:53
"However, the way the standard is written, it is explicitly dependent on them (see the SQL test statements)."

You are right in that we should probably update the way the NSG profile provided their examples and remove references to spatialite extensions. The data validity constraints are fine, but the SQL statement examples should not reference those spatialite extensions.

I think that going the custom extension/custom code route seems to be the best solution in this case.

**Comment by melvchan** [comment] 2018-04-30 12:33
@gramnation , thank you for pointing this out. We have begun writing some custom internal code for the ETS, but will take a look at what GDAL did and see if this is something we can utilize.

**Comment by dstenger** [comment] 2018-05-22 13:21
@keshav-nangare Can you please do investigations?

**Comment by ajanett** [comment] 2018-05-22 18:55
I already have custom code that will perform these tests w/o spatialite but have been unable to test it in this revision of ETS geoPackage because all feature tests are being excluded. Am posting another issue on that now.

**Comment by ajanett** [comment] 2018-05-22 20:13
We need to remove the test NSG 19B on "features" from the NSG ETS GeoPackage and this needs to be grouped with the other feature geometry tests within the OGC GeoPackage tests.

**Comment by dstenger** [comment] 2018-05-23 14:35
As far as I see spatialite cannot be added as a Maven dependency (Java library) but must be installed on OS and loaded by driver then.

Thus, removing the spatialite functions from tests keeps the test suite far more comprehensive.

@ajanett You are very much welcome to provide your custom code via pull request.

**Comment by ajanett** [comment] 2018-05-31 16:26
We will be initiating the pull request to this NSG geopackage soon to remove this test. 
However, the nsg geopackage tests are built upon the OGC geopackage tests, and the pull request: https://github.com/opengeospatial/ets-gpkg12/pull/62
corrects this issue within the OGC Geopackage tests and performs these tests without the use of spatialite extensions.

**Closed** 2018-06-25 13:46 UTC
Labels: question, status:waiting
